"""create tasks table

Revision ID: 718aade9cd57
Revises: 
Create Date: 2024-04-26 00:48:07.491950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718aade9cd57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
